/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ArtistsArtistIdIndexRouteImport } from './routes/artists/$artistId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdIndexRoute = ArtistsArtistIdIndexRouteImport.update({
  id: '/artists/$artistId/',
  path: '/artists/$artistId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/home': typeof HomeIndexRoute
  '/artists/$artistId': typeof ArtistsArtistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/home': typeof HomeIndexRoute
  '/artists/$artistId': typeof ArtistsArtistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/home/': typeof HomeIndexRoute
  '/artists/$artistId/': typeof ArtistsArtistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artists' | '/home' | '/artists/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artists' | '/home' | '/artists/$artistId'
  id: '__root__' | '/' | '/artists/' | '/home/' | '/artists/$artistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ArtistsArtistIdIndexRoute: typeof ArtistsArtistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId/': {
      id: '/artists/$artistId/'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ArtistsArtistIdIndexRoute: ArtistsArtistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
